# External dependencies for running Fairspace
external:
  keycloak:
    baseUrl: http://keycloak.local
    realm: fairspace
    clientId: workspace-client
    clientSecret: '**********'

# Settings for Fairspace
fairspace:
  name: "Local Fairspace"
  description: "Local Fairspace"
  ingress:
    domain: fairspace.local
    tls:
      enabled: false
  features:
    - ExtraStorage
    - LlmSearch
  services:
    JupyterHub: http://jupyterhub.local/user/${username}/lab

# Specific settings for Saturn subchart
saturn:
  # loglevel: debug
  image:
    image: saturn-local
    tag: latest
    pullPolicy: Never
  persistence:
    extra-file-storage:
      size: 5Gi

# Specific settings for Pluto subchart
pluto:
  # logLevel: debug
  image:
    image: pluto-local
    tag: latest
    pullPolicy: Never
  responseTimeoutMillis: 600000  # 10 minutes
  connectTimeoutMillis: 2000
  maxFileSize: 1GB
