apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-saturn
  labels:
    app: saturn
    {{- include "fairspace.labels" . | nindent 4 }}
data:
  application.yaml: |-
    port: 8090
    livenessPort: 8091
    publicUrl: {{ template "fairspace.url" . }}
    llmConversationPath: "/data/saturn/conversations"
    jena:
      metadataBaseIRI: http://{{ .Values.fairspace.ingress.domain }}/iri/
      datasetPath: "/data/saturn/db"
      storeParams:
{{ toYaml .Values.saturn.storeParams | indent 8 }}
      transactionLogPath: "/data/saturn/files/log"
      bulkTransactions: {{ .Values.saturn.bulkTransactions }}
    auth:
      authServerUrl: {{ .Values.external.keycloak.managementUrl | default .Values.external.keycloak.baseUrl }}/
      realm: {{ .Values.external.keycloak.realm }}
      clientId: {{ .Values.external.keycloak.clientId }}
      enableBasicAuth: {{ .Values.saturn.auth.enableBasicAuth }}
      superAdminUser: {{ .Values.external.keycloak.superAdminUser | default (printf "organisation-admin-%s" .Values.external.keycloak.realm ) }}
{{ if .Values.saturn.auth.defaultUserRoles }}
      defaultUserRoles:
{{ toYaml .Values.saturn.auth.defaultUserRoles | indent 8 }}
{{ end }}
    webDAV:
      blobStorePath: "/data/saturn/files/blobs"
    viewDatabase:
      enabled: true
    services:
{{ toYaml .Values.fairspace.services | indent 6 }}
    features:
{{ toYaml .Values.fairspace.features | indent 6 }}
{{ if has "ExtraStorage" .Values.fairspace.features }}
    extraStorage:
      blobStorePath: "/data/saturn/extrafiles/blobs"
{{ end }}

  vocabulary.ttl: |
{{ if .Values.saturn.vocabulary -}}
{{ .Values.saturn.vocabulary | indent 4 -}}
{{ else -}}
{{ .Files.Get "vocabulary.ttl" | indent 4 -}}
{{ end }}
  views.yaml: |
{{ if .Values.saturn.views -}}
{{ .Values.saturn.views | indent 4 -}}
{{ else -}}
{{ .Files.Get "views.yaml" | indent 4 -}}
{{ end }}
